name: CI
env:
  micromamba_version: 1.3

on:
  push:
  pull_request:
  workflow_dispatch: # allows you to trigger manually

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'false'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          paths_ignore: '["**/docs/**"]'

  build:
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    name: python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: open-radar-data-dev
          environment-file: ci/environment.yml
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: Set up conda environment
        run: |
          python -m pip install -e .
          conda list
      - name: Run Tests
        run: |
          python -m pytest --cov=./ --cov-report=xml --verbose
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3.1.3
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
